version: '2'
services:

  jupyter:
    image: ${IMAGE_JUPYTER}
    restart: always
    container_name: jupyter
    ports:
      - "${PORT_JUPYTER}:8888"
    volumes:
      - "${LOCAL_DOCKER_VOLUMES}${DATA_JUPYTER}:/home/jovyan/work"

networks:
  default:
    external:
      name: local-sandbox-networks