version: '2'
services:

  portainer:
    image: ${IMAGE_PORTAINER}
    restart: always
    container_name: portainer
    ports:
      - "${PORT_PORTAINER}:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${LOCAL_DOCKER_VOLUMES}${DATA_PORTAINER}:/data"

networks:
  default:
    external:
      name: local-sandbox-networks