version: '2'
services:

  nats:
    restart: always
    image: ${IMAGE_NATS}    
    container_name: nats
    ports:
      - "4222:4222"
      - "6222:6222"
      - "${PORT_NATS}:8222"
  nats-1:
    image: ${IMAGE_NATS}
    container_name: nats-1
    command: "--cluster local-sandbox-networks://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    
  nats-2:
    image: ${IMAGE_NATS}
    container_name: nats-2
    command: "--cluster local-sandbox-networks://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"

networks:
  default:
    external:
      name: local-sandbox-networks

    