version: '2'
services:

  metabase:
    restart: always
    image: ${IMAGE_METABASE}
    container_name: metabase
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    ports:
      - "${PORT_METABASE}:3000"
    volumes:
      - "${LOCAL_DOCKER_VOLUMES}${DATA_METABASE}:/metabase-data"

networks:
  default:
    external:
      name: local-sandbox-networks