version: '2'
services:

  vault:
    image: ${IMAGE_VAULT}
    container_name: vault
    ports:
      - "${PORT_VAULT}:8200"
    restart: always
    volumes:
      - "${LOCAL_DOCKER_VOLUMES}${DATA_VAULT}:/vault"
      - ./vault-config.json:/vault/config/vault.json
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json

networks:
  default:
    external:
      name: local-sandbox-networks