version: '3.4'  
services:

  elasticsearch:
    container_name: elasticsearch
    restart: always
    image: ${IMAGE_ELK_ELASTIC}
    ports:
      - "${PORT_ELK_ELASTIC}:9200"
    volumes:  
      - ${DATA_ELASTIC_DATA}:/usr/share/elasticsearch/data
    environment:  
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node

  kibana:
    container_name: kibana
    restart: always
    image: ${IMAGE_ELK_KIBANA}
    ports:
      - "${PORT_ELK_KIBANA}:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://localhost:${PORT_ELK_ELASTIC}

networks:
  default:
    external:
      name: local-sandbox-networks

volumes:
  elasticsearch_data:
